### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by maeyama-s** [maeyama-s/furima_29807#11]
・フリマアプリのURL
　　https://furima-29807.herokuapp.com/
・Basic認証のIDとパスワード
　　ID→『maeyama』、パスワード→『1258』
・出品者用のメールアドレスとパスワード
　　メールアドレス→『mae@email』、パスワード→『maeyama06』
・購入者用のメールアドレスとパスワード
　　メールアドレス→『mio@email』、パスワード→『miomiomio0』
・購入用カードの番号・期限・セキュリティコード
　　番号→『4242424242424242』、期限→『2024年3月』、セキュリティコード『123』

**Comment by ryszw** [comment]
前山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
